config/routes.rb
CcProject::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :team_invitations


  get "static_pages/search_user"

  get "static_pages/about"

  resources :distance_essentials

  resources :teams


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
  #extend FriendlyId
  #friendly_id :login
  #validates_format_of :login, :with => /\A[a-z0-9]+\z/i
  #friendly_id :user
  #validates_format_of :user, :with => /\A[a-z0-9]+\z/i

  validates :name, :presence =>true
  validates :roles, :presence =>true

  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :role_ids

  has_many :distance_essentials, :dependent => :destroy
  has_many :teams, through: :team_invitations, :uniq => true
  has_and_belongs_to_many :coached_teams, :class_name => "Team", :join_table => "coached_teams_coaches", :uniq => true
  has_many :team_invitations, :dependent => :destroy


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource 
  before_filter :authenticate_user!


  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
    @teams = Team.all
  end

  def show
    @user = User.find(params[:id])
    @uservds = @user.distance_essentials
    
    #respond_to do |format|
    #   format.json {render json: @uservds}
    #end
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

<%= link_to 'All Distance Essentials', distance_essentials_path %>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @teams.each do |team| %>
  <tr>
    <td><%= team.name %></td>
    <td><%= link_to 'Show', team %></td>
	<% if current_user.has_role? :admin %>
    <td><%= link_to 'Edit', edit_team_path(team) %></td>
    <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<%end%>
	<% if current_user.has_role? :coach %>
    <td><%= link_to 'Edit', edit_team_path(team) %></td>
    <td><%= link_to 'Destroy', team, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<%end%>
  </tr>
<% end %>
</table>

app/views/users/show.html.erb
<h2 class="indent">User Profile</h2>
  <p class="indent"> <b>User:</b> <%= @user.name %> </p>
  <p class="indent"> <b>Email:</b> <%= @user.email if @user.email %> </p>
<div class="indentb">
<table id="team_distance_essentials">
 <thead>
  <tr>
    <th>Team</th>
    <th>Date</th>
    <th>Diet Quality Score</th>
    <th>Hours of Sleep</th>
    <th>Minutes Running</th>
    <th>Minutes Stretching</th>
    <th>Minutes Icing</th>
    <th>Core strength</th>
    <th>Upper Body Weights</th>
    <th>Minutes Cross Training</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
 </thead>
 <tbody>
<% @uservds.each do |distance_essential| %>
  <tr>
    <td><%= distance_essential.team.name %></td>
    <td><%= distance_essential.date %></td>
    <td><%= distance_essential.diet_quality %></td>
    <td><%= distance_essential.hours_of_sleep %></td>
    <td><%= distance_essential.minutes_run %></td>
    <td><%= distance_essential.minutes_streching %></td>
    <td><%= distance_essential.minutes_icing %></td>
    <td><%= distance_essential.core_strength %></td>
    <td><%= distance_essential.upper_body_weights %></td>
    <td><%= distance_essential.minutes_cross_training %></td>
    <td><%= link_to 'Show', distance_essential %></td>
    <td><%= link_to 'Edit', edit_distance_essential_path(distance_essential) %></td>
    <td><%= link_to 'Destroy', distance_essential, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
 </tbody>
</table>
</div>