config/routes.rb
CcProject::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :team_invitations


  get "static_pages/search_user"

  get "static_pages/about"

  resources :distance_essentials

  resources :teams


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  
  resources :users

end

app/models/team_invitation.rb
class TeamInvitation < ActiveRecord::Base
  belongs_to :user
  belongs_to :team
  
  validates :email, :presence =>true
  validates :team, :presence =>true

  attr_accessor :email
  attr_accessible :team_id, :email
  before_create :associate_user
  private
  def associate_user
    user = User.where(:email => self.email).first
    if user.blank?
      # Create new user if it doesn't exist.
      new_user = User.new(:email => self.email, :password => Devise.friendly_token[0,20])
      new_user.save!
     
      # Associate the newly created user with the invitation
      self.user = new_user
    else
      self.user = user
    end
  end
end

app/controllers/team_invitations_controller.rb
class TeamInvitationsController < ApplicationController
  load_and_authorize_resource
  # GET /team_invitations
  # GET /team_invitations.json
  def index
    @team_invitations = TeamInvitation.where(:team_id => current_user.coached_teams)
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @team_invitations }
    end
  end

  # GET /team_invitations/1
  # GET /team_invitations/1.json
  def show
    @team_invitation = TeamInvitation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team_invitation }
    end
  end

  # GET /team_invitations/new
  # GET /team_invitations/new.json
  def new
    @team_invitation = TeamInvitation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team_invitation }
    end
  end

  # GET /team_invitations/1/edit
  def edit
    @team_invitation = TeamInvitation.find(params[:id])
  end

  # POST /team_invitations
  # POST /team_invitations.json
  def create
    @team_invitation = TeamInvitation.new(params[:team_invitation])

    respond_to do |format|
      if @team_invitation.save
        format.html { redirect_to @team_invitation, notice: 'Team invitation was successfully created.' }
        format.json { render json: @team_invitation, status: :created, location: @team_invitation }
      else
        format.html { render action: "new" }
        format.json { render json: @team_invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /team_invitations/1
  # PUT /team_invitations/1.json
  def update
    @team_invitation = TeamInvitation.find(params[:id])

    respond_to do |format|
      if @team_invitation.update_attributes(params[:team_invitation])
        format.html { redirect_to @team_invitation, notice: 'Team invitation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team_invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_invitations/1
  # DELETE /team_invitations/1.json
  def destroy
    @team_invitation = TeamInvitation.find(params[:id])
    @team_invitation.destroy

    respond_to do |format|
      format.html { redirect_to team_invitations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/team_invitations_helper.rb
module TeamInvitationsHelper
end

app/views/team_invitations/_form.html.erb
<%= simple_form_for(@team_invitation) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :email %>
    <%= f.association :team, :collection => current_user.coached_teams %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/team_invitations/edit.html.erb
<h2 class="indent">Editing Team Invitation</h2>
<div class="indentb">
<%= render 'form' %>

<%= link_to 'Show', @team_invitation %> |
<%= link_to 'Back', team_invitations_path %>
</div>

app/views/team_invitations/index.html.erb
<h2 class="indent">Team Invitations</h2>
<div class="indent">
<table>
  <tr>
    <th>User</th>
    <th>Team</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @team_invitations.each do |team_invitation| %>
  <tr>
    <td><%= team_invitation.user.name %></td>
    <td><%= team_invitation.team.name %></td>
    <td><%= link_to 'Show', team_invitation %></td>
    <td><%= link_to 'Edit', edit_team_invitation_path(team_invitation) %></td>
    <td><%= link_to 'Destroy', team_invitation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<p><%= link_to 'New Team invitation', new_team_invitation_path %></p>


<p><%= link_to 'See Registered Players', static_pages_search_user_path %></p>  
</div>

app/views/team_invitations/new.html.erb
<h2 class="indent">New Team Invitation</h2>
<div class="indentb">
<%= render 'form' %>

<%= link_to 'Back', team_invitations_path %>
</div>

app/views/team_invitations/show.html.erb
<div class="indent">
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @team_invitation.user.name %>
</p>

<p>
  <b>Team:</b>
  <%= @team_invitation.team.name %>
</p>


<%= link_to 'Edit', edit_team_invitation_path(@team_invitation) %> |
<%= link_to 'Back', team_invitations_path %>
</div>