config/routes.rb
CcProject::Application.routes.draw do
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :team_invitations


  get "static_pages/search_user"

  get "static_pages/about"

  resources :distance_essentials

  resources :teams


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  
  resources :users

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <%= content_tag :div, msg, :id => "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<style type="text/css" id=>

#yo a:link {color:#BABAD4; }
#yo a:active {color:#BABAD4;}
#yo a:visited {color:#BABAD4;}
#yo a:hover {color: white;}
</style>


<div style="position:absolute;background-color:#30307e; width:100%;height: 45px;margin-bottom: emCalc(30);"></div>


<div id="indentb">
<% if user_signed_in? %>
<nav class="top-bar" >
  <ul class="title-area" >
    <li class="name top-bar-sections"><h1 style="font-family:serif;"><a><%= link_to "XC", root_path%></a></h1></li>
    <li class="toggle-topbar menu-icon fuckthepolice"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="left">
      <li class="divider"></li>
      <li class="has-dropdown active">
      <a>Profile</a>
        <ul class="dropdown">
          <li class="active"><%= link_to 'Profile', user_path(current_user) %></li>
          <li class="active"><%= link_to 'New Distance Essential', new_distance_essential_path %></li>
        </ul>
      </li>
         
      <li class="divider"></li>
      <li class="active"><%= link_to 'Team', teams_path %></li>
      <li class="divider"></li>
    </ul>
    <ul class="right">
      <li class="divider"></li>
      <li class="has-dropdown active">
      <a>Account</a>
        <ul class="dropdown">
          <li class="active"><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
          <li class="active"><%= link_to 'Edit Account', edit_user_registration_path %></li>
        </ul>
      </li>
      <li class="divider"></li>

      <% if current_user.has_role? :admin %>
      <!--<li class="active">
        <%= link_to 'Old Admin', users_path %>
      </li>-->
      <li class="active">
        <%= link_to 'Admin', rails_admin_path%>
      </li>
      <% end %>
    </ul>
  </section>
</nav>


<%else%>
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1 style="font-family:serif;"><a><%= link_to "XC", root_path%></a></h1>
    </li>
    <li class="toggle-topbar menu-icon fuckthepolice"><a href="#"><span>Menu</span></a>
    </li>
  </ul>
  <section class="top-bar-section">
    <ul class="right" >
        <li class="divider"></li>
        <li class="active"><%= link_to "About", static_pages_about_path%></li>
        <li class="divider"></li>
        <li class="active"><%= link_to 'Sign up', new_user_registration_path %></li>
        <li class="divider"></li>
        <li class="active"><%= link_to "Login", new_user_session_path%></li>
        <li class="divider"></li>
    </ul>
  </section>
</nav>
<%end%>
</div>




<!--
<ul  id="yo" class="nav" style="background-color:#30307e; box-shadow: 2px 2px 2px #888888;">
<div class="indentb" style="text-align:right;">
  <li style="font-size:1.8em; margin-left:1%; "><%= link_to "CC", root_path, :class => 'brand' %></li>
  <% if user_signed_in? %>
    <li style="margin-right:.5%;">
        <%= link_to 'Profile', user_path(current_user) %>
    </li>
    <li style="margin-right:.5%;">
	<%= link_to 'New Distance Essential', new_distance_essential_path %>
    </li>
    <li style="margin-right:.5%;">
    <%= link_to 'Team', teams_path %>
    </li>
    <li style="margin-right:.5%;">
    <%= link_to 'Edit Account', edit_user_registration_path %>
    </li>
   
    <% if current_user.has_role? :admin %>
      <li style="margin-right:.5%;">
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>

  <% else %>
    <li style="margin-right:.5%;">
      <%= link_to 'About', static_pages_about_path %>
    </li>
    <li style="margin-right:.5%;">
      <%= link_to 'Sign up', new_user_registration_path %>
    </li style="margin-right:.5%;">
  <% end %>
    <% if user_signed_in? %>
    <li >
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
</div>
  <% end %>
</ul>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "XCTM" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Cc Project" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div id="container" class="container">
      <header>
        <%= render 'layouts/navigation' %>
        <%= render 'layouts/messages' %>
      </header>
      <div id="main" role="main">
        <%= yield %>
      </div>
      <footer>
      </footer>
    </div> <!--! end of #container -->
    <%= javascript_include_tag "application" %>
  </body>
</html>